### ISSUE TITLE
Kubernetes v1.29.x Upgrade

### ISSUE THREAD

**Issue by cswaas** [alex1989hu/kubelet-serving-cert-approver#185]
Hi,
I'm building a Kubernetes cluster according to this blog:
https://mirceanton.com/posts/2023-11-28-the-best-os-for-kubernetes/

It is referring to your repo.

Any intention to upgrade for Kubernetes v.1.29.x anytime soon? It comes with the current vesrion of Talos OS v.1.6.0.
Or, would it work anyway?

By the way, I'm also from Zurich.

Best regards,
Christian

**Comment by alex1989hu** [comment]
Dear @cswaas, I have just released [0.8.0](https://github.com/alex1989hu/kubelet-serving-cert-approver/releases/tag/v0.8.0) which supports (and E2E tests against) Kubernetes v1.29.

However, [0.7.7](https://github.com/alex1989hu/kubelet-serving-cert-approver/releases/tag/v0.7.7) works fine with Kubernetes v1.29 as well - there wasn't any breaking change around certificate request approval.

Greetings from 👋 Zurich, hope we see each other on the Kubernetes Community Day Zürich 2024

Best,
Alex

**Comment by cswaas** [comment]
Dear @alex1989hu, thanks for the quick response.

Kubernetes Community Day Zürich 2024 seems being sold out already (https://tickets.kcdzurich.ch/). 

Best regards and viszontlátásra!
Christian
